### ISSUE TITLE
[Bug] Config Screen is broken

### ISSUE THREAD

**Issue by Wudji** [fantahund/DurabilityViewer#1]
![image](https://github.com/fantahund/DurabilityViewer/assets/93850120/daba041d-d572-45b0-8c8a-8b18321ea5e5)

**Comment by fantahund** [comment]
Is fixed in the latest Modrinth release.
https://modrinth.com/mod/durability-viewer-updated/version/1.20.1-1.11.0

**Comment by fantahund** [comment]
Is fixed in the latest Modrinth release.
https://modrinth.com/mod/durability-viewer-updated/version/1.20.1-1.11.0
